# Generated by Django 3.2.8 on 2021-10-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20211021_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
